action_pattern: ^<answer>(.*?)</answer>$
think_action_pattern: <think>(.*?)</think>\s*<answer>(.*?)</answer>
user_prompt_no_think_format: <answer> [your answer] </answer>
user_prompt_think_format: <think> [Your thoughts] </think> <answer> [your answer] </answer>

max_tokens_per_step: 128
max_actions_per_traj: 10
default_history_length: 5

env_manager_cls: roll.pipeline.agentic.env_manager.step_env_manager.StepEnvManager
custom_env:
  SimpleSokoban:
    env_type: sokoban
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_no_think_format}
    env_manager_cls: ${env_manager_cls}
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config: # keys should be a subset of SokobanConfig
      env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer must be one of action in a turn, format is <answer>Right</answer>"
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      dim_x: 6
      dim_y: 6
      num_boxes: 1
  LargerSokoban:
    env_type: sokoban
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_no_think_format}
    env_manager_cls: roll.pipeline.agentic.env_manager.step_env_manager.StepEnvManager
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config:
      env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer must be one of action in a turn, format is <answer>Right</answer>"
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      dim_x: 8
      dim_y: 8
      num_boxes: 2
      search_depth: 10
  SokobanDifferentGridVocab:
    env_type: sokoban
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_no_think_format}
    env_manager_cls: roll.pipeline.agentic.env_manager.step_env_manager.StepEnvManager
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config: # keys should be a subset of SokobanConfig
      env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer must be one of action in a turn, format is <answer>Right</answer>"
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      search_depth: 30
      dim_x: 6
      dim_y: 6
      num_boxes: 1
      grid_lookup: { 0: "W", 1: ".", 2: "G", 3: "C", 4: "B", 5: "A", 6: "@" }
      grid_vocab: { "W": "wall", ".": "empty", "G": "target", "C": "box on target", "B": "box", "A": "player", "@": "player on target" }
  FrozenLake:
    env_type: frozen_lake
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_no_think_format}
    env_manager_cls: roll.pipeline.agentic.env_manager.step_env_manager.StepEnvManager
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config:
      env_instruction: "You are solving the FrozenLake puzzle. Forbid the whole and go to the target. You may move to the unintended direction due to the slippery ice. The answer must be one of action in a turn, format is <answer>Right</answer>"
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      is_slippery: false
  FrozenLakeThink:
    env_type: frozen_lake
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_think_format}
    env_manager_cls: roll.pipeline.agentic.env_manager.step_env_manager.StepEnvManager
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config:
      env_instruction: "You are solving the FrozenLake puzzle. Forbid the whole and go to the target. You may move to the unintended direction due to the slippery ice. The answer must be one of action in a turn, format is <answer>Right</answer>"
      action_pattern: ${think_action_pattern}
      max_steps: ${max_actions_per_traj}
      is_slippery: false
  WebShopEnv:
    env_type: webshop
    max_tokens_per_step: ${max_tokens_per_step}
    user_prompt_format: ${user_prompt_no_think_format}
    env_manager_cls: ${env_manager_cls}
    use_thread_lock: true
    history_length: ${default_history_length}
    agent_system_template: ${agent_system_template}
    agent_template: ${agent_template}
    env_config:
      observation_mode: text
      max_steps: ${max_actions_per_traj}

agent_system_template: |
  You're a helpful assistant. You are a good game player. You are aiming to get high reward in the game.

agent_template: |
  ## Env Instruction: {env_instruction}
  
  ## State Description: 
  Prior to this step, you have completed {step_count} steps. 
  Recent History: Below are the most recent {history_length} observations, the corresponding actions you took, and the environmental reward feedback:
  [{history}]
  
  Current State:
  You are currently at step {current_step}. Your current observation is: [{current_observation}]
  
  ## Output Format Requirement: 
  Your response *must* strictly adhere to the following format: <answer> [your answer] </answer>, like <answer> [your answer] </answer>, with no extra text.
  Response Length Limit: Your output must not exceed {max_response_length} words (tokens).
  
  Determine the Next Action:
